### ISSUE TITLE
listing received shares does not work

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-reva#11]
einstein shares a folder to marie

marie should:
1. see the incoming folder in the list of incoming shares
2. see the incoming folder in her home folder
3. be able to navigate into the shared folder
4. be able to read files from the shared folder

what happens:
- nothing :(

**Comment by C0rby** [comment]
Progess:
- [x] 1. see the incoming folder in the list of incoming shares
- [ ] 2. see the incoming folter in her home folder
- [ ] 3. be able to navigate into the shared folder
- [ ] 4. be able to read files from the shared folder

**Comment by PVince81** [comment]
@C0rby is this done ? I see one checkbox not ticked.

Also, we need to:

- [ ] enable the tests blocke by issue-ocis-reva-11

**Comment by PVince81** [comment]
hmmm I ran the tests but none passed, so there is likely more issues to look at...

**Comment by PVince81** [comment]
I think we should look at those tests as there might be tags missing, for example I see some COPY operation tests that fail because the permission checks are not implement, but is missing the tag for the matching ticket.

@individual-it

**Comment by C0rby** [comment]
> @C0rby is this done ? I see one checkbox not ticked.

Depends if reading means showing it in phoenix or downloading.
If showin in phoenix then it's done, if it means downloading then no. https://github.com/owncloud/ocis-reva/issues/359

**Comment by PVince81** [comment]
Listing means showing it up. I saw this working for OC storage and EOS storage.
