### ISSUE TITLE
run litmus tests in CI

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#120]
run passing litmus tests in CI
see #18

**Comment by dpakach** [comment]
Tests to run
- [ ] Basic
- [ ] Basic
- [ ] Basic

**Comment by individual-it** [comment]
done for now, will have to check again when the other tests pass

**Comment by individual-it** [comment]
litmus tests are implemented in CI, failing/missing tests tracked in following issues

- locks (not implemented): owncloud/ocis-reva#172
- checksums (not implemented): owncloud/ocis-reva#196
- private links (not implemented): owncloud/ocis-reva#216
- quota (not implemented): owncloud/ocis-reva#101
