### ISSUE TITLE
File list doesn't loads when a file contains &

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis-reva#122]
### Steps to reproduce
1. Setup ocis-phoenix with ocis-reva backend
2. upload some files eg .`lorem.txt` and `new-lorem.txt`
3. Create a new file that contains `&` character in its name eg. `&#`

### Result
The file gets created in the data folder but the file list is empty

### description
The reason for this error seems to be because  phoenix cannot parse the xml response from the webdav api when it contains such files.
If we have such file in the middle of the file list then some files show up in the list (the files that come before the one containing `&`) while the other files (the files that are after the one containing `&` in the list) are not shown.

***This might be the problem with server as well since the server sent correct and parseable response before.***

**Comment by individual-it** [comment]
fix done, need to add API tests (or enable if they exist)

**Comment by individual-it** [comment]
tests added in https://github.com/owncloud/core/pull/37231

as the change is not in ocis / ocis-reva yet, the tests for ocis demonstrate the current buggy behaviour when the fix will be brought into ocis-reva and ocis, the tests will start failing and will have to be adjusted
