### ISSUE TITLE
Run tests in parallel in drone CI

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis-reva#123]
Currently we run all tests in single pipeline in CI. 
When the volume of the tests increases it will take longer time to  complete.
It would be better to run tests in different pipelines in parallel to reduce CI runtime.

**Comment by individual-it** [comment]
currently we are running 2 parts, see https://github.com/owncloud/ocis-reva/pull/421/files#diff-74dc60589e0610c07e491b31f8693b2bR5
closing?

**Comment by phil-davis** [comment]
Yes, fine by me to close. We run:
- local API acceptance tests in its own pipeline
- core API acceptance tests split into 2 separate pipelines

If eithher of these start taking too long in the future then it is easy to split into more parts.
