### ISSUE TITLE
create test-skeleton folder on user creation

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#167]
creating a user with a skeleton folder is not implemented, so tests that expect a skeleton folder to exist fail, to fix that we need ether to rewrite all tests that use the skeleton folder or create one e.g. by coping the files to the known location

**Comment by PVince81** [comment]
the skeleton feature in OCIS is not planned for the MVP milestone.

for the affected tests, I suggest to rewrite them.
I suggest we start with https://github.com/owncloud/ocis-reva/issues/14 so we get unblocked there

**Comment by individual-it** [comment]
@PVince81 @HariBhandari07 is in the process to fix the test-infrastructure so it will emulate the skeleton feature, simply by copying the files (no need to implement it in OCIS)
We are doing the same in the UI tests in phoenix when running with ocis

**Comment by PVince81** [comment]
@individual-it is there a WIP PR for visibility ?

**Comment by individual-it** [comment]
https://github.com/owncloud/core/pull/37363
