### ISSUE TITLE
Preserve mtime after TUS upload

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#174]
For a PUT request it was always possible to pass in a header "X-OC-Mtime" to specify the mtime of the uploaded file.

Since the addition of TUS upload, Phoenix is already sending the mtime in the Upload-Metadata metadata, but that value is not passed along.

- [x] pass along X-OC-Mtime mtime value to storage's TUS metadata: https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocdav/put.go#L257
- [x] tus.go must also honor the "mtime" metadata and pass it along to the storage: https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocdav/tus.go#L56

Now I'm not sure whether we store it as "arbitrary metadata" there or whether there is another way streamlined with the storage (like `touch`)

@butonic

**Comment by butonic** [comment]
Just Touch the file

**Comment by PVince81** [comment]
> the eos driver currently does not support setting arbitrary metadata

raised here: https://github.com/owncloud/ocis-reva/issues/189

**Comment by PVince81** [comment]
I've added to the MVP project as mtime preservation was already on the roadmap

**Comment by PVince81** [comment]
- [ ] BUG: to investigate: even a regular Webdav PUT is not preserving the mtime even though it's returning "X-OC-Mtime: accepted"

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/ocis-reva/issues/273 for adding related API test

**Comment by PVince81** [comment]
PR for propagating mtime in chunked mode: https://github.com/cs3org/reva/pull/841

**Comment by PVince81** [comment]
- [ ] enable test

**Comment by individual-it** [comment]
@PVince81 this is closed but tests are not enabled yet. reopen, or is there an other ticket?

**Comment by PVince81** [comment]
- PRs for tests:
   - https://github.com/owncloud/core/pull/37589
   - https://github.com/owncloud/core/pull/37589

**Comment by individual-it** [comment]
the PR you have mentioned is only for the public link upload, for normal upload the PRs are
https://github.com/owncloud/core/pull/37553
https://github.com/owncloud/core/pull/37607

**Comment by PVince81** [comment]
this is the actual ticket: https://github.com/owncloud/ocis-reva/issues/273
