### ISSUE TITLE
listing shares via ocs API is not possible

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#21]
1. upload file textfile.txt into the home folder
2. create a share with `curl 'http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares' -u user1:1234 --data 'shareType=0&shareWith=user0&path=%2Fhome%2Ftextfile.txt&permissions=1'`
3. try to retrieve the share information via ocs api `curl -u user1:1234 'http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Fhome%2Ftextfile.txt&reshares=true' | xmllint --format -`

### result:
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data/>
</ocs>
```

phoenix does not show existing shares

### expected result:

something similar like oC10:
```
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message/>
    <totalitems/>
    <itemsperpage/>
  </meta>
  <data>
    <element>
      <id>364</id>
      <share_type>0</share_type>
      <uid_owner>admin</uid_owner>
      <displayname_owner>admin</displayname_owner>
      <permissions>19</permissions>
      <stime>1579672946</stime>
      <parent/>
      <expiration/>
      <token/>
      <uid_file_owner>admin</uid_file_owner>
      <displayname_file_owner>admin</displayname_file_owner>
      <path>/textfile0.txt</path>
      <item_type>file</item_type>
      <mimetype>text/plain</mimetype>
      <storage_id>home::admin</storage_id>
      <storage>1</storage>
      <item_source>48</item_source>
      <file_source>48</file_source>
      <file_parent>9</file_parent>
      <file_target>/textfile0.txt</file_target>
      <share_with>uu1</share_with>
      <share_with_displayname>uu1</share_with_displayname>
      <share_with_additional_info/>
      <mail_send>0</mail_send>
      <attributes/>
    </element>
  </data>
</ocs>
```

trying to share the same file with the same user again results in 
`<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>996</statuscode><message>grpc create share request failed</message></meta></ocs>`

**Comment by individual-it** [comment]
now I receive an invalid xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>996</statuscode><message>grpc stat request failed</message></meta></ocs><?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>996</statuscode><message>fixme</message></meta></ocs>

**Comment by PVince81** [comment]
the retrieval works now, discovered in https://github.com/owncloud/ocis-reva/issues/238

- [ ] rerun the tests
- [ ] raise issue for creating a share over an existing one
