### ISSUE TITLE
ocs v2 endpoint still returns ocs v1 status codes

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#26]
compare results of `ocs/v1.php` and `ocs/v2.php` endpoint
e.g.  `curl  http://localhost:9140/ocs/v1.php/config -u user0:123456  | xmllint --format -`

both endpoints return 
```
 <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
```

but the v2 endpoint should return status-code `200` that is the same as the HTTP status code

**Comment by individual-it** [comment]
when trying to access the users endpoint with an authenticated user but one that is different to the one that is requested  e.g. `http://localhost:9140/ocs/v1.php/cloud/users/user1 -u user0:123456` its opposite, the OCS status code is `403` in both cases but the HTTP status code is `200`

**Comment by individual-it** [comment]
not existing endpoints but with an authorised user return HTTP `200` and OCS `998` on both v1.php and v2.php

**Comment by PVince81** [comment]
@C0rby I see you fixed part of it in https://github.com/cs3org/reva/pull/696

what's left to do ? a checkbox list might be useful

**Comment by C0rby** [comment]
Those are the last tests that still need some work.

tests/acceptance/features/apiAuth/cors.feature:1
tests/acceptance/features/apiShareManagementBasic/createShare.feature:37
tests/acceptance/features/apiShareManagementBasic/createShare.feature:76
tests/acceptance/features/apiShareManagementBasic/createShare.feature:194
tests/acceptance/features/apiShareManagementBasic/createShare.feature:224
