### ISSUE TITLE
API test for mtime preservation

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#273]
Check that whenever we pass a "X-OC-Mtime" header in an upload with a value that lies in the past (maybe a year earlier), that the mtime is properly applied to the file after querying it using PROPFIND after the upload.

To test compliance it should be sufficient to have a test using a Webdav PUT as it will confirm whether all the backends (OC and EOS) are accepting the value.

The test should be reusable for OC 10 as mtime preservation exists there as well.
Optionally, a similar test could be added for web UI to confirm that the UI upload code is sending that header, would require creating skeleton/local files with a past mtime.

Related to https://github.com/owncloud/ocis-reva/issues/174

@individual-it FYI

**Comment by PVince81** [comment]
actually to test if chunked upload also properly preserves mtime, one could use a Phoenix test with big files and a chunk size specified in config.json

**Comment by individual-it** [comment]
for a chunking upload which of the requests has to have the header set?

**Comment by PVince81** [comment]
- non-chunked: send "X-OC-Mtime" on the single Webdav PUT
- for TUS chunk upload: send "mtime" in the "Upload-Metadata" header of the initial POST, base64 encoded, for example: `Upload-Metadata: filename cGxhdGZvcm0tdG9vbHNfcjI5LjAuNS1saW51eC56aXA=,filetype YXBwbGljYXRpb24vemlw,size ODExNjY3NQ==,mtime MTU3MjM2NTE5MC45MTk=`

**Comment by kiranparajuli589** [comment]
WebUI tests for mtime preservation are not quite possible now. During test upload process, resources are zipped and then uploaded to selenium server then uploaded to oC from there. While zipping (in phoenix using `archiver` library), the `mtime` of the resource is reset.

**Comment by individual-it** [comment]
lets close this for now as the API tests are implemented in https://github.com/owncloud/core/pull/37553 and UI tests prove to be more difficult but not high priority currently

**Comment by PVince81** [comment]
did we enable the tests already or are they still disabled ?

**Comment by individual-it** [comment]
They are still disabled https://github.com/owncloud/core/search?q=issue-ocis-reva-174&unscoped_q=issue-ocis-reva-174
I think there was confusion which ticket tracks what.
Reopening this one to enable tests

@Talank please enable the tests marked with `@issue-ocis-reva-174` on ocis & ocis-reva
