### ISSUE TITLE
Public link upload-only permissions should prevent download

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#285]
Test case in apiSharePublicLink1/createPublicLinkShare.feature scenario "try to download from a public share that has upload only permissions"

The file content is returned instead of 404.

This was tested against the public link branch: https://github.com/cs3org/reva/pull/822

@micbar @refs FYI

**Comment by refs** [comment]
Permissions were left out of the main implementation bulk in purpose

**Comment by PVince81** [comment]
also for delete operations it returns 500 instead of 403. let's handle those in the context of this ticket as well

**Comment by PVince81** [comment]
superseded by more general ticket https://github.com/owncloud/ocis-reva/issues/292
