### ISSUE TITLE
OCS expiration date should accept date without time component

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#288]
### Steps

Run the tests from tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature

### Expected

Public link shares are created.

### Actual
Error 996 returned by API.

### Logs
```
2020-06-18T14:00:10+02:00 ERR invalid date format error="parsing time \"2020-06-21\" as \"2006-01-02T15:04:05Z0700\": cannot parse \"\" as \"T\"" pkg=rhttp service=reva traceid=8f353347d444c7e282f8d4004203129d
```

We should also allow passing a date without time component like the old API allowed.

**Comment by PVince81** [comment]
need to check how OC 10 handles such dates internally, whether it receives midnight UTC time or midnight in the local timezone. I suspect it might use midnight UTC time as I remember reports about expiration happening too early.

We should first align with the old implementation  and later on solve the timezone topic.

**Comment by PVince81** [comment]
In OC 10 https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Controller/Share20OcsController.php#L1102 we used `\DateTime` to parse the expiration date: https://www.php.net/manual/en/datetime.construct.php
It accepts both a date or a datetime.

And later in the code the time is set to zero anyway. This means that the expiration date will be based on the server's timezone, which is usually UTC.

For now let's align OCIS' behavior with this and later on we can improve timezone expectations.

**Comment by PVince81** [comment]
@LukasHirt does Phoenix include a time component in the expiration date ?

**Comment by LukasHirt** [comment]
AFAICT we are using always ISO standard and we are setting the time to the end of the day of the creation.

**Comment by PVince81** [comment]
as long as the user doesn't see the time or expects anything, let's keep it that way.

I'll first align the APIs as currently time handling would be tricky due to timezone issues.

**Comment by PVince81** [comment]
PR here https://github.com/cs3org/reva/pull/918

**Comment by PVince81** [comment]
PR merged, next up:
- [ ] enable matching tests

**Comment by phil-davis** [comment]
In ownCloud10 the expiration date-time is set to the expiry date (e.g. 2020-07-08) at time 00:00:00 (i.e. the very start of the day) = 2020-07-08:00:00:00.

The comparison is done in https://github.com/owncloud/core/blob/master/lib/private/Share20/Manager.php#L178 `shareHasExpired()`

The expiry date-time is compared with `DateTime("today")`, which is the 00:00:00 of today. And the share is only consider expired if the expiry date-time strictly `<DateTime("today")` So, for example, at 2020-07-08:23:30:00 the share expiry date-time is 2020-07-08:00:00:00 and the "today"  of 2020-07-08:23:30:00 is 2020-07-08:00:00:00 and so the share has not expired.

The stored expiry of 2020-07-08:00:00 is interpreted to mean that the share is valid until 2020-07-08:23:59:59.999999 and that the actual moment that the share becomes expired i 2020-07-09:00:00:00

**Comment by PVince81** [comment]
tests enabled in https://github.com/owncloud/core/pull/37633
