### ISSUE TITLE
OCS public link support for legacy publicUpload attribute

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#289]
Currently we have only implemented passing permissions as either "role" or "permissions" attributes, but not the even more old "publicUpload" attribute.

@butonic 

The tests from tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLink.feature are using this intensively.

Maybe we could rewrite those tests to use "permissions" instead and have another single test for only testing the legacy value ?

Might be related to https://github.com/owncloud/ocis-reva/issues/233

@individual-it thoughts ?

**Comment by individual-it** [comment]
some tests even use both, how the the publicUpload works together with the permissions?

**Comment by PVince81** [comment]
see https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Controller/Share20OcsController.php#L775 for the logic.

it seems that it's only relevant if no "permissions" attribute was set.
if you set both, the code tells me that "permissions" has priority

**Comment by individual-it** [comment]
Then we maybe have to improve the tests anyway. Looks like we sometimes set both and sometimes not

**Comment by PVince81** [comment]
I think it is easy to add in Reva, so we don't need to urgently touch all these tests.

**Comment by PVince81** [comment]
never mind, no quick win there as all affected tests are also blocked by the inability to reshare and update link shares...

**Comment by PVince81** [comment]
- [ ] PR here for adding the feature to reva: https://github.com/cs3org/reva/pull/853
- [ ] unskip tests

**Comment by PVince81** [comment]
it's in ocis-reva 0.6.0
