### ISSUE TITLE
Public link response share_with special value when password set

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#294]
In OC 10 the fields share_with and share_with_displayname in the OCS response contain "***redacted***" as we don't want to expose the password.

In OCIS these fields are empty.

We should return the same value there as the UI uses it to determine whether a password was set or not to offer password clearing.

This is likely simply about changing the response string in the public link code path in shares.go

**Comment by phil-davis** [comment]
Note: the full value is `***redacted***`
e.g. https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Controller/Share20OcsController.php#L225

**Comment by PVince81** [comment]
How to access the public share object to find out if a password is set, here https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go#L1354 ?

@refs do you know ?

**Comment by PVince81** [comment]
tried to cast `share` to `conversions.PublicShare` but it says `invalid type assertion: share.(conversions.PublicShare) (non-interface type *collaborationv1beta1.Share on left)`

**Comment by PVince81** [comment]
never mind, I thought the code path was the same.
looking at `PublicShare2ShareData` now

**Comment by PVince81** [comment]
PR here https://github.com/cs3org/reva/pull/904

**Comment by refs** [comment]
@PVince81 can this be closed?

**Comment by PVince81** [comment]
no, we need to enable the matching tests

- [ ] enable tests

**Comment by PVince81** [comment]
Test enabled here https://github.com/owncloud/core/pull/37633
