### ISSUE TITLE
Public share URL truncated in response

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#336]
### Steps

1. Create a public link share
1. Copy public link and extract the token
1. Get the share with curl using its token: https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/$TOKEN
1. Look at the "url" field

### Expected result
Full URL present

### Actual result
URL is missing its prefix and doesn't start with http

Many sharing tests are checking the URL and also some clients use it from here, so we should fix it.
In the code it relies on the "Origin" header, but that one is not always set, at least not when called on API level.

@refs FYI

**Comment by refs** [comment]
this is an opportunity to normalize the json driver with the users share json driver and use UUID in both. ticket here https://github.com/owncloud/ocis-reva/issues/339

**Comment by refs** [comment]
@PVince81 mentioned that the url is present on `config.json`, if there is no way to get Origin, we might need to use this value. We can do this from the browser thanks to the Origin header. The response we're sending from the API is not correct.

I could validate this behavior by adding an `Origin` header to a request:

Request:
```bash
curl 'https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Fdistributed-services-with-go_b1_0.pdf&reshares=true' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'authorization: Bearer eyJhbGciOiJQUzI1NiIsImtpZCI6IiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJwaG9lbml4IiwiZXhwIjoxNTkzNzgzNzQ2LCJqdGkiOiJVVk16YjRHQ0hhdVNlSU1Bb3dEZUlRRjhsdC13dktHOSIsImlhdCI6MTU5Mzc4MzE0NiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6OTIwMCIsInN1YiI6Ilh0U2lfbWl5V1NCLXBrdkd
ueFBvQzVBNGZsaWgwVUNMZ3ZVN2NMd2ptakNLWDdGWW4ySFdrNnJSQ0V1eTJHNXFBeV95TVFjX0ZLOWFORmhVTXJYMnBRQGtvbm5lY3QiLCJrYy5pc0FjY2Vzc1Rva2VuIjp0cnVlLCJrYy5hdXRob3JpemVkU2NvcGVzIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJlbWFpbCJdLCJrYy5pZGVudGl0eSI6eyJrYy5pLmRuIjoiRWluc3RlaW4iLCJrYy5pLmlkIjoiY24
9ZWluc3RlaW4sb3U9dXNlcnMsZGM9ZXhhbXBsZSxkYz1vcmciLCJrYy5pLnVuIjoiZWluc3RlaW4ifSwia2MucHJvdmlkZXIiOiJpZGVudGlmaWVyLWxkYXAifQ.AdfS-YgfL8MJWb8N7PZyl933yr_pj1bGsnMgEqRHFFPDN2TNmiRIsqRYL93gDfkV29Yi1kYrB6D9wEH6rzFo-hE0420eed9vdUH1mxa3R_AB_Bd5BE-el7D971rFY9S7PnnrxObFqS0cwtTjnT0Y
E498cdTzOA3p_fVkab07pjjhQ-e6xa9E93v7x-crlkF6Zy6-ZHJMZRUUEHo5YNBqw2S3fpXlRCUBAnIaBcVSVDMadls9Joe4zNW_kxbfH1xGX-UO9KGoqwjpfCFE8OGVqP4eZ26JFoKrhLcFk9c2vWGSvU4Pw8nF23sJ0N7xXqglb_LGdK2_MaaUo1O1n9nztA' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' \
  -H 'OCS-APIREQUEST: true' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'Accept: */*' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://localhost:9200/' \
  -H 'Accept-Language: en,es-ES;q=0.9,es;q=0.8' \
  -H 'Origin:https://EXAMPLE.COM' \
  --compressed \
  --insecure | xmllint --format -
```

Response:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <element>
      <id>nZXGYAnLunrr</id>
      <share_type>3</share_type>
      <uid_owner>einstein</uid_owner>
      <displayname_owner>Einstein</displayname_owner>
      <permissions>1</permissions>
      <stime>1593768254</stime>
      <parent/>
      <expiration/>
      <token>ijHqniAbHCEO</token>
      <uid_file_owner>einstein</uid_file_owner>
      <displayname_file_owner>Einstein</displayname_file_owner>
      <additional_info_owner/>
      <additional_info_file_owner/>
      <state>0</state>
      <path>/distributed-services-with-go_b1_0.pdf</path>
      <item_type>file</item_type>
      <mimetype>application/pdf</mimetype>
      <storage_id>1284d238-aa92-42ce-bdc4-0b0000009154</storage_id>
      <storage>0</storage>
      <item_source>0f84b311-65ae-423a-bd54-a78015394f87</item_source>
      <file_source>0f84b311-65ae-423a-bd54-a78015394f87</file_source>
      <file_parent/>
      <file_target>/distributed-services-with-go_b1_0.pdf</file_target>
      <share_with_additional_info/>
      <mail_send>0</mail_send>
      <name>test</name>
      <url>https://EXAMPLE.COM//#/s/ijHqniAbHCEO</url>
    </element>
  </data>
</ocs>
```

**Comment by PVince81** [comment]
I wonder if we even have access to that information, the base URL.
If not we should probably add it somewhere in the config as it will be useful for many service.

In OC 10 we used to have some "CLI URL" field in the config that was used for any process that did not interact with the browser, like cron jobs for activities or notifications that needed to contain URLs.

**Comment by refs** [comment]
> I wonder if we even have access to that information, the base URL.
> If not we should probably add it somewhere in the config as it will be useful for many service.
> 
> In OC 10 we used to have some "CLI URL" field in the config that was used for any process that did not interact with the browser, like cron jobs for activities or notifications that needed to contain URLs.

if we can't infer origin from the browser it needs to be configured imho.

**Comment by PVince81** [comment]
- [ ] Fix PR here: https://github.com/cs3org/reva/pull/945
- [ ] Enabling tests here: https://github.com/owncloud/core/pull/37662
