### ISSUE TITLE
File id and file source not looking the same

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#344]
### Steps

1. Open the network console in the browser
1. Create a folder "test"
1. Refresh the page
1. Check the Webdav response and take note of the "oc:fileid" value
1. Share "test" with another user
1. Check the "POST" response to OCS for that creation and take note of the "file_source" value

### Expected
Both values of "file_source" and "oc:fileid" are the same.

### Actual
Different value formats:
- fileid looks like "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjkzYTQxYTU3LTI0YzQtNDQ1Yy04ZDVkLTJiZDYxYmFiODY3MA=="
- file_source looks like c72e3d65-0782-488f-8708-0ca70b84d00a

This makes it impossible for clients to correlate share entries with Webdav results.

@butonic was this on purpose or is it a bug ?

cc @refs

**Comment by refs** [comment]
I came across this in one of my first deep dives into the code. The base64 encoded contains `storage_id:resource_id`, decoding it results in:

```
echo MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjkzYTQxYTU3LTI0YzQtNDQ1Yy04ZDVkLTJiZDYxYmFiODY3MA== | base64 --decode
1284d238-aa92-42ce-bdc4-0b0000009154:93a41a57-24c4-445c-8d5d-2bd61bab8670
```

leaving `resource_id`, which semantically I understand is the `file_id` as `93a41a57-24c4-445c-8d5d-2bd61bab8670`, quite not matching the `file_source`.

If they both *MUST* be the same, then it looks like a bug.

**Comment by PVince81** [comment]
I saw some utility code called `wrapResourceID`, maybe that one is missing for the shares

**Comment by PVince81** [comment]
preparing PR, trivial thing...

**Comment by PVince81** [comment]
PR here https://github.com/cs3org/reva/pull/951
