### ISSUE TITLE
"data" is empty after public link share 

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/ocis-reva#375]
To reproduce the issue:

1. from ocis repo start phoenix `bin/ocis server` . For details about the setup, check the section `run tests > with Ocis backend` https://owncloud.github.io/clients/web/testing/

2. upload a file or a folder 

`curl -X PUT http://localhost:9140/remote.php/webdav/hari.txt -d "123" -u user1:1234`

3. make sure the file is uploaded

`curl -X PROPFIND http://localhost:9140/remote.php/webdav/hari.txt -u user1:1234 | xmllint --format -`

4. create a public share

`curl -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -u user1:1234 -d "permission=31&path=hari.txt&shareType=3" | xmllint --format -`

5. now get info about the shares created by the user
` curl -X GET http://localhost:9140/ocs/v2.php/apps/files_sharing/api/v1/shares -u user1:1234 | xmllint --format -`

Here, the `data` is empty
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>200</statuscode>
    <message>OK</message>
  </meta>
  <data/>
</ocs>
```
Also, `shares.json` is empty (`{}`).

**Comment by PVince81** [comment]
note: public shares are stored in "publicshares.json"

strange issue, I thought this would work so maybe this specific case is not covered yet by tests ?

make sure you have redis running if you're using the OC storage, otherwise the shares don't appear @HariBhandari07

**Comment by HariBhandari07** [comment]
@PVince81  redis is running.

**Comment by PVince81** [comment]
can you add or extend an API test to trigger this issue ?

**Comment by HariBhandari07** [comment]
@PVince81  this issue was caused because of the content of `publicshares.json`. When the file is deleted and steps in the issue are tried again, it behaves differently. So, closing.
