### ISSUE TITLE
Increase the number of core API acceptance tests being run

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis-reva#415]
After core PR https://github.com/owncloud/core/pull/37736 and ocis-reva PR https://github.com/owncloud/ocis-reva/pull/402 are merged, and similar "expected failures file" is implemented in `cs3org/reva`, check the core scenarios tagged `toImplementOnOCIS`.

Where possible/reasonable, remove the tag in core. This will make them run in OCIS/reva CI. Add them to `EXPECTED_FAILURES_FILE`. Make sure CI still passes.

The objective is to have as many tests as "reasonable" running in OCIS/reva CI. "reasonable" includes:
- keep the total run-time of the CI pipelines  in the 15-20 minute maximum range (e.g. split into multiple pipelines...)
- there might be test scenarios that really do "completely explode" because some things that they expect are "completely not there yet" in OCIS. That might "explode the whole test suite". So either improve the error handling in the core acceptance test code, or do not enable such tests yet.

**Comment by phil-davis** [comment]
Issue https://github.com/owncloud/ocis/issues/518 is getting the sharing tests sorted out to run more reasonably on OCIS.

I just need to review what other non-sharing core API scenarios are still tagged `toImplementOnOCIS` - we need to remove as many of those tags as possible.

**Comment by dpakach** [comment]
@phil-davis I am going to look into this issue there are few more failing tests that can be enabled

**Comment by phil-davis** [comment]
Now there are just tests tagged `toImplementOnOCIS` for things like:
- subadmins managing group membership
- creating/deleting... groups with some strange characters or slash in their name - those mess up CI because sometimes the group can be created but not deleted, and so later scenarios end up with extra weird groups
- case-sensitive groups - having "finance" and "Finance" be different groups. That can also be some trouble for the test code to cleanup the groups

Those are OK for now. There are only 31 occurrences of `toImplementOnOCIS` - so we can easily find them when these things are addressed/decided.
