### ISSUE TITLE
Share state is always "accepted" in listUserShares

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#450]
See https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go#L1433

There is no code path that ever populates the ShareData's "state" field, so it defaults to 0 (accepted) and the UI will always display it as accepted.

I suspect that the pending shares code path wasn't fully implemented yet, especially considering that the CS3 type "collaboration.Share" doesn't contain any information about the share state.

@C0rby @labkode @butonic can you confirm ?

**Comment by butonic** [comment]
ok 1433 does not set the state, so it defaults to true. but why can I see the pending shares in the "shared with me" ui in phoenix with the option to accept / deny shares. Investigating who is actually calling `userShare2ShareData`  and if the share data is updated elsewhere.

**Comment by C0rby** [comment]
It's those lines: https://github.com/cs3org/reva/blob/72380a687765495fa0c15fcfcba102cab058c0ae/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go#L1057-L1066

**Comment by butonic** [comment]
`listSharesWithMe` is setting the state in https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go#L1057-L1066

Should we initialize the state as `-1` in https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go#L1433 to be sure?

**Comment by PVince81** [comment]
yeah, if setting to -1 can make the field disappear from the response

**Comment by PVince81** [comment]
never mind. I saw this working correctly for OC storage and EOS today on ocis master
