### ISSUE TITLE
when sharing a folder to a user the default permissions are "1"

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#46]
default permissions when sharing a folder to a user should be `31`

**Comment by butonic** [comment]
related discussion: https://github.com/owncloud/core/issues/11707

@pmaier1 should we make the default configurable in ocis? or stick to rw? or go with a more secure r?

**Comment by pmaier1** [comment]
> @pmaier1 should we make the default configurable in ocis? or stick to rw? or go with a more secure r?

The reason for having configurable default permissions in oC10 was that users can only change the permissions **after** creating a share. As we took care of this in Phoenix by allowing users to set all the share properties **before** creating a share this has less importance. It would make a good feature to allow setting a default role for user shares but right now I consider this as nice-to-have. If we have to set a default, I'd take the secure read-only way.

**Comment by PVince81** [comment]
> If we have to set a default, I'd take the secure read-only way.

in this case it means we'd need to adjust the test to accept "1" as default

**Comment by individual-it** [comment]
ToDo:
- [ ] find an API test that checks the default permissions in oC10 (if there is none add one)
- [ ] create a separate test for ocis, that checks that the default permission is 1 in ocic, tag with this issue (but don't write a note about deleting the scenario when fixing the issue, because it will not be fixed)

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiShareManagementBasic/createShare.feature around line 198 onwards:
```
Scenario Outline: Creating a share of a folder with a user, the default permissions are all permissions(31)
```

https://github.com/owncloud/core/blob/master/tests/acceptance/features/webUISharingInternalUsers2/adminDisablesSharePermissions.feature
has scenarios where the admin adjusts the default sharing permissions.

**Comment by PVince81** [comment]
@C0rby if to review, can you link to the PR here ? thanks

**Comment by C0rby** [comment]
Right now Hugo still has to review it upstream.
Now thinking of it that means I should already put this ticket to `to review`.

**Comment by PVince81** [comment]
@C0rby can you link to the upstream PR ? else it's difficult to find when reading this ticket here

**Comment by C0rby** [comment]
I must have forgot this ticket, because I linked to all other ones.
