### ISSUE TITLE
make steps that check the PROPFIND response less specific

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#471]
OCIS storage tests like `apiOcisSpecific/apiWebdavProperties2-getFileProperties.feature:65` fail because the order of responses are different that expected

`And the value of the item "//d:response[2]/d:href" in the response to user "Alice" should match "/remote\.php\/<expected_href>\/file1.txt/"`
if the response has that file1.txt in the first item the test would fail, but the response actually is fine

**Comment by phil-davis** [comment]
Suggestion https://github.com/owncloud/ocis-reva/pull/473#issuecomment-691124478

Instead of "Then the value of the item "//d:response[1]/d:href"" would likely better to say something like "there is an entry with href XYI in the response"

I will make a more generic test step.

**Comment by PVince81** [comment]
blocks https://github.com/owncloud/ocis-reva/issues/471
