### ISSUE TITLE
add desktop & mobile client ids for the oidc provider

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-reva#5]
eg for the desktop:
```
[http.services.oidcprovider.clients.xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69]
#http://localhost:20080/oauth2/auth?response_type=code&client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&redirect_uri=http://localhost:56122&code_challenge=6TU6waVV6PbI3tw1vrUnECiYiKnTdrpK8hLFlcwfiVo&code_challenge_method=S256&scope=openid%20offline_access&prompt=consent
#http://localhost:56122/?error=invalid_state&error_description=The+state+is+missing+or+has+less+than+8+characters+and+is+therefore+considered+too+weak&error_hint=Request+parameter+%22state%22+must+be+at+least+be+8+characters+long+to+ensure+sufficient+entropy.&state=
id = "xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69"
redirect_uris = ["http://localhost:56122"]
grant_types = ["implicit", "refresh_token", "authorization_code", "password", "client_credentials"]
response_types = ["code"] # use authorization code flow, see https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead for details
scopes = ["openid", "profile", "email", "offline", "offline_access"]
#public = true # force PKCS for public clients
client_secret = "$2y$12$pKsCQPp8e/UOL1QDQhT3g.1J.KK8oMJACbEXIqRD0LiOxvgey.TtS"
```

but the desktop has no fixed port for the redirect_uris ... so how do we preregister it? @DeepDiver1975 care to investigate?

**Comment by butonic** [comment]
from the ory/fosite example:
```

	// GetRequestURIs is an array of request_uri values that are pre-registered by the RP for use at the OP. Servers MAY
	// cache the contents of the files referenced by these URIs and not retrieve them at the time they are used in a request.
	// OPs can require that request_uri values used be pre-registered with the require_request_uri_registration
	// discovery parameter.
	GetRequestURIs() []string
```

so `require_request_uri_registration` seems to be a thing. checking the official spec ...

https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata

> request_uris
> OPTIONAL. Array of `request_uri` values that are pre-registered by the RP for use at the OP. Servers MAY cache the contents of the files referenced by these URIs and not retrieve them at the time they are used in a request. OPs can require that `request_uri` values used be pre-registered with the `require_request_uri_registration` discovery parameter.
> If the contents of the request file could ever change, these URI values SHOULD include the base64url encoded SHA-256 hash value of the file contents referenced by the URI as the value of the URI fragment. If the fragment value used for a URI changes, that signals the server that its cached value for that URI with the old fragment value is no longer valid.

and the https://openid.net/specs/openid-connect-discovery-1_0-16.html#ProviderMetadata

> require_request_uri_registration
> OPTIONAL. Boolean value specifying whether the OP requires any request_uri values used to be pre-registered using the request_uris registration parameter. Pre-registration is REQUIRED when the value is true.

so might be a config option on the server side

**Comment by DeepDiver1975** [comment]
Is this using konnectd?

**Comment by butonic** [comment]
no. currently the reva oidc, but the spec says the redirect_uri must match the one that is registered. but the client randomly chooses a port ...

**Comment by TheOneRing** [comment]
Making assumptions about available ports on a desktop system is kind of hard so it would be awesome if we can keep the random port.

**Comment by DeepDiver1975** [comment]
as per spec redirect uri to localhost are free to use any port.

but honestly - we better use a proper idp instead of some self brewd thingy ....

**Comment by butonic** [comment]
> as per spec redirect uri to localhost are free to use any port.
can you point me to right place?

> but honestly - we better use a proper idp instead of some self brewd thingy ....
I agree

**Comment by DeepDiver1975** [comment]
on http and alternative schema: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

about ports (not THE spec - but this is common practice) https://www.oauth.com/oauth2-servers/oauth-native-apps/redirect-urls-for-native-apps/

**Comment by DeepDiver1975** [comment]
we have konnectd now *almost* intrgrated into ocis ... we can close this soonish
