### ISSUE TITLE
Add configuration for redirect URIs using env variable

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis-reva#58]
Current the phoenix redirect uris are hard coded in https://github.com/owncloud/ocis-reva/blob/fb0af32920ff1c12a2e31c1d55a50c157b7ba1e5/pkg/command/frontend.go#L158

We need to be able to configure that using env variables.

**Comment by DeepDiver1975** [comment]
kopano konnectd will soon come to ocis and replace this hand crafted oidc provider. 
you can pass in a config file there then ....

**Comment by butonic** [comment]
konnectd has been merged and updated in ocis.
