### ISSUE TITLE
security headers not served when downloading a file

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#66]
expectation:
```
    When user "user0" downloads file "/welcome.txt" using the WebDAV API
    Then the following headers should be set
      | header                            | value                                                            |
      | Content-Disposition               | attachment; filename*=UTF-8''welcome.txt; filename="welcome.txt" |
      | Content-Security-Policy           | default-src 'none';                                              |
      | X-Content-Type-Options            | nosniff                                                          |
      | X-Download-Options                | noopen                                                           |
      | X-Frame-Options                   | SAMEORIGIN                                                       |
      | X-Permitted-Cross-Domain-Policies | none                                                             |
      | X-Robots-Tag                      | none                                                             |
      | X-XSS-Protection                  | 1; mode=block                                                    |
```

reality:
```
GET /remote.php/dav/files/oc/user0/welcome.txt HTTP/1.1
Host: localhost:9140
User-Agent: Guzzle/5.3.1 curl/7.58.0 PHP/7.1.33-4+ubuntu18.04.1+deb.sury.org+1
Authorization: Basic dXNlcjA6MTIzNDU2

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: text/plain; charset=utf-8
Etag: "b2687d94ff8a8246711efd6b69f4f947"
Last-Modified: Thu, 30 Jan 2020 12:05:20 +0545
Oc-Etag: "b2687d94ff8a8246711efd6b69f4f947"
Oc-Fileid: MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjU1NDQwMDAwOmZiYTE5OGViLTRlZjMtNDE4Zi1hYmEyLWEwMmE1YmE5NTA5YQ==
Vary: Origin
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTgwMzY4ODIwLCJpYXQiOjE1ODAzNjUyMjAsInVzZXIiOnsiaWQiOnsib3BhcXVlX2lkIjoidXNlcjAifSwidXNlcm5hbWUiOiJ1c2VyMCIsIm1haWwiOiJ1c2VyMEBleGFtcGxlLm9yZyIsImRpc3BsYXlfbmFtZSI6IlVzZXIgWmVybyJ9fQ.CEU0b4MyeSGswPARMfimrKOLeExpDRF9BrtJ13vFsEk
Date: Thu, 30 Jan 2020 06:20:20 GMT
Content-Length: 52

Welcome this is just an example file for developers.
```

**Comment by PVince81** [comment]
downloading a file through ocdav is done in the GET handler: https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocdav/get.go#L35

one could add the missing headers in the response

as far as I understand their values are simply hard coded, but it would be good to check / search the code to see if some are configurable

**Comment by karakayasemi** [comment]
As far as I see, oc10 set these headers as hard coded to all responses with `.htaccess` if mod_env module enabled.
https://github.com/owncloud/core/blob/b58749af75249b1f1aac75436a3f19e935c3c0ae/.htaccess#L17

IMHO, we need to set these headers with a middleware to all webdav responses instead of setting them for only downloads. We have already a middleware for this purpose in ocis-pkg and ocis-webdav is using it.
https://github.com/owncloud/ocis-pkg/blob/82ad5938d2a514fb07e3038d9294b7a36add811a/middleware/header.go#L36

However, as far as I understand currently webdav requests are handling by reva and ocis-webdav is not working yet. As a solution, we can also add a new http middleware to reva project. If it is a valid approach, I would like to work on it.

**Comment by butonic** [comment]
@karakayasemi In the long run we went to move the ocdav and ocs services from reva to ocis-ocs and ocis-webdav. they are owncloud specific and don't really belong in reva anyway. 

As a first step, adding them to a middleware in reva makes sense to hale it working ASAP. so yeah, go ahead!

**Comment by PVince81** [comment]
released with ocis 1.0.0-beta5

need to check if there are any tests that can be enabled now

**Comment by karakayasemi** [comment]
ocis tests are passed for the scenario in this test pr: https://github.com/owncloud/ocis/pull/304.

As far as I understand the process, the next step is merging https://github.com/owncloud/core/pull/37485 and closing https://github.com/owncloud/ocis/pull/304

**Comment by PVince81** [comment]
yes, correct
