### ISSUE TITLE
CI fails on push events

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#72]
![image](https://user-images.githubusercontent.com/2425577/73634770-0d40c080-468a-11ea-9b73-7a7a15e5a694.png)

**Comment by individual-it** [comment]
@butonic could you help here?

**Comment by tboerger** [comment]
Just fix the changelog files.

**Comment by individual-it** [comment]
could you give me a hint about what is wrong with the files?

**Comment by tboerger** [comment]
https://github.com/owncloud/ocis-reva/blob/master/changelog/unreleased/change-default-namespace.md is the problem, EVERY changelog file must have a primary link which points in best case to an issue, in worst case just to an PR.
